image: gcc:latest

# Define commands that run before each job's script
before_script:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -
  - apt-get update && apt-get install -y software-properties-common
  - apt-add-repository "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main"
  - apt-get update && apt-get install -y clang
  - cd LinkedList
  - wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp

gcc:
  script:
  - g++ test.cpp -std=c++17 -Wall -Wextra -Wpedantic -o test
  - ./test
clang:
  script:
  - clang++ test.cpp -std=c++17 -Wall -Wextra -Wpedantic -o test
  - ./test
   