image: gcc:latest

# Define commands that run before each job's script
before_script:
  - apt-get update && apt-get install -y clang 
  #cmake --allow-unauthenticated
  - wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp
  - ls

# Try to compile our sample hello world app
compile:
  script:
  - g++ LinkedList/test.cpp -Wall -Wextra -Wpedantic -o test
  - ./test
  # Save the compiled output from the above for downloading via GitLab and in Gitlab 8.6 to use in future build steps
  #artifacts:
    #paths:
    #- list