image: gcc:latest

# Define commands that run before each job's script
before_script:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -
  - apt-get update && apt-get install -y software-properties-common
  - apt-add-repository "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main"
  - apt-get update && apt-get install -y clang
  - cd LinkedList
  - wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp

gcc:
  script:
  - g++ test.cpp -std=c++17 -Wall -Wextra -Wpedantic -o test
  - ./test
clang:
  script:
  - clang++ test.cpp -std=c++17 -stdlib=libstdc++ -Wall -Wextra -Wpedantic -o test
  - ./test
gcc-address:
  script:
  - g++ test.cpp -std=c++17 -g -Wall -Wextra -Wpedantic -fsanitize=address -fno-omit-frame-pointer -o test
  - ./test   
gcc-ub:
  script:
  - g++ test.cpp -std=c++17 -g -Wall -Wextra -Wpedantic -fsanitize=undefined -o test
  - ./test   
clang-address:
  script:
  - clang++ test.cpp -std=c++17 -stdlib=libstdc++ -g -Wall -Wextra -Wpedantic -fsanitize=address -fno-omit-frame-pointer -o test
  - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-8/bin/llvm-symbolizer ./test
clang-memory:
  script:
  - clang++ test.cpp -std=c++17 -stdlib=libstdc++ -g -Wall -Wextra -Wpedantic -fsanitize=memory -fno-omit-frame-pointer -fsanitize-memory-track-origins -o test
  - MSAN_SYMBOLIZER_PATH=/usr/lib/llvm-8/bin/llvm-symbolizer ASAN_OPTIONS=detect_leaks=1 ./test
  allow_failure: true
clang-ub:
  script:
  - clang++ test.cpp -std=c++17 -stdlib=libstdc++ -g -Wall -Wextra -Wpedantic -fsanitize=undefined  -o test
  - ./test