image: gcc:latest

# Define commands that run before each job's script
before_script:
  - apt-get update && apt-get install -y clang 
  - cd LinkedList
  - wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp

# Try to compile our sample hello world app
compile:
  script:
  - g++ test.cpp -Wall -Wextra -Wpedantic -o test
  - ./test