image: gcc:latest

# Define commands that run before each job's script
before_script:
  - apt-get update && apt-get install -y clang 
  - cd /usr/local/include/
  - wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp
  - cd ~/LinkedList

# Try to compile our sample hello world app
gcc:
  script:
  - g++ test.cpp -Wall -Wextra -Wpedantic -o test
  - ./test
clang:
  script:
  - clang++ test.cpp -Wall -Wextra -Wpedantic -o test
  - ./test
   